name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org/'
          node-version: 20.9.0
          cache: 'npm'

      - name: Install npm packages
        run: npm install

      - name: Unit tests
        run: npm test

      - name: Build Logger
        run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: logger
          path: ./dist/

      - name: Publish NPM package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}